name: selftest
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  links:
    permissions:
      contents: read
      issues: write
      pull-requests: read
    uses: ./.github/workflows/check-links.yml
