name: Check Links (reusable)

on:
  workflow_call:
    inputs:
      lychee-config:
        type: string
        default: ''
      create-issue-on-main:
        type: boolean
        default: true
      skip-label:
        type: string
        default: 'links checked by hand'

jobs:
  link-checker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: d-morrison/gha/check-links@v1
        with:
          lychee-config: ${{ inputs.lychee-config }}
