name: Check Non-Standard Characters (reusable)

on:
  workflow_call:
    inputs:
      python-version:
        description: Python version to set up.
        type: string
        default: '3.x'

jobs:
  check-chars:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Check for non-standard characters
        uses: d-morrison/gha/check-non-standard-chars@v1
        with:
          python-version: ${{ inputs.python-version }}
